### ISSUE TITLE
Add APS data to REDCap

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/detect_pilot_test_1y#37]
# Overview

If Morri decides to go this route, we will add the APS data to a REDCap database. We would do this to eliminate the need to share files through shared folders and reduce the risk of accidentally pushing data to GitHub.

# Tasks

- [x] Sign up for a REDCap account. There are actually two choices here. [UTHealth](https://redcap.uth.tmc.edu/index.php?action=myprojects) has a REDCap instance and the [School of Public Health](https://redcap.sph.uth.edu/) also has a REDCap instance. For either, you need to request access. I'm not aware of any big differences between the two instances. I think the UTHealth instance might be running a slightly newer version of REDCap. All else being equal, we may want to use that one.
- [x] Create a REDCap project that can store the data.
- [x] Add Brad to the project.
- [ ] Import the raw data into REDCap.
- [x] Request an API for the project.
- [x] Test importing data into R/Python via the API.
- [ ] Document the process in an SOP/Continuity Guide.

**Comment by corvidfox** [comment]
I don't think I can edit the tasks here in GitHub if I did not create the task. I can assign, label, add milestones, adjust status, link pull requests, set priority, close, and delete... but not edit. It doesn't seem to give me an option to check off any of the tasks, either.

**Comment by corvidfox** [comment]
Sent pull request with the updated redcap_data_prep.py script. I'm sure there are some better ways to go about what I did, but it's been running smoothly and easily reproduces the processing on my dummy data.

A few questions/thoughts at this point of the task:

1. Do we want any of the dummy data I've created, the manually-finalized REDCap data dictionaries, or the processed dummy data to be pushed on GitHub? There isn't any identifiable information that I am aware of (I just filled it with randomly generated junk in the same general format/parameters I saw in the source). I'll be keeping them local unless told otherwise.

2. Do we want to have two separate REDCap projects (one for APS, one for MedStar), or a combined "project"? I think I can make a combined "project" work. I set the Data Dictionaries to actually help me keep track of them if we did do a combined "project," anticipating the possibility.

3. What is the expectation for processing and uploading the data to REDCap? In playing with my "test project," it seems that there is an API option so long as permissions are enabled, or direct CSV upload. Processing can potentially happen without any storage on my local machine, if I have an accessible path to access the file and an accessible path to write the output files (and then read them for the API upload, which given the size may be have to be in chunks). I appreciate the guidance on those next steps.

**Comment by corvidfox** [comment]
DONE from list:

- [x] Sign up for a REDCap account. There are actually two choices here. [UTHealth](https://redcap.uth.tmc.edu/index.php?action=myprojects) has a REDCap instance and the [School of Public Health](https://redcap.sph.uth.edu/) also has a REDCap instance. For either, you need to request access. I'm not aware of any big differences between the two instances. I think the UTHealth instance might be running a slightly newer version of REDCap. All else being equal, we may want to use that one.
- [x] Create a REDCap project that can store the data.
- [x] Add Brad to the project. @mbcann01 

Prep for Import Done:
- [x] Separate "Test" Project in REDCap created
- [x] Manually created "dummy" versions of source data with small number of observations containing entirely randomly generated data of similar format for testing
- [x] Python script (redcap_data_prep.py) to process data for upload to REDCap created
- [x] Python script (redcap_data_prep.py) tested with "dummy" data
- [x] Python environment dependencies and documentation generated
- [x] Python files reorganized
- [x] Processed "dummy data" successfully imported to "Test" REDCap Project, readily accessible with API call
- [x] API token for REDCap Merging project requested

To Do:

- [ ] Process the source data
- [ ] Upload the source data to REDCap
- [ ] Test access of source data in REDCap with API calls
- [ ] Complete documentation of entire process

**Comment by mbcann01** [comment]
@corvidfox, are you able to check off the tasks that I created in the first section of this issue yet? If not, I will try to change your permissions again.

**Comment by mbcann01** [comment]
@corvidfox I just bumped you up to a higher privilege set. Do you mind trying again when you get a chance?

**Comment by corvidfox** [comment]
@mbcann01 It works! I clicked off what I have done, and will go through the other tasks to ensure I'm checking off things appropriately. Thank you!

**Comment by corvidfox** [comment]
Not necessary at this time; code in place to complete if required in the future
