### ISSUE TITLE
Add MedStar data to REDCap

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/detect_pilot_test_1y#38]
# Overview

If Morri decides to go this route, we will add the MedStar data to a REDCap database. We would do this to eliminate the need to share files through shared folders and reduce the risk of accidentally pushing data to GitHub.

# Tasks

- [x] Sign up for a REDCap account. There are actually two choices here. [UTHealth](https://redcap.uth.tmc.edu/index.php?action=myprojects) has a REDCap instance and the [School of Public Health](https://redcap.sph.uth.edu/) also has a REDCap instance. For either, you need to request access. I'm not aware of any big differences between the two instances. I think the UTHealth instance might be running a slightly newer version of REDCap. All else being equal, we may want to use that one.
- [x] Create a REDCap project that can store the data.
- [x] Add Brad to the project.
- [ ] Import the raw data into REDCap.
- [x] Request an API for the project.
- [x] Test importing data into R/Python via the API.
- [ ] Document the process in an SOP/Continuity Guide.

**Comment by corvidfox** [comment]
no longer considered necessary; code in place to complete if required in the future
